### PR TITLE
function which plots histograms from data

### PR DESCRIPTION
**Pull request by Szymon-Gut**
Function with description, and tests.

### CODE REVIEW

**Comment by maciejors** [comment]
Looks grand overall, but there are issues with the tests which I believe should be addressed.

The first two tests get skipped every time because there are no `expect_ ...` functions called inside. i'm not sure what you meant to test there but perhaps a function like `expect_no_error` can prove useful here.

The other tests fail with the following errors:
```r
Error (test-plot_hist_vars.R:17:3): Function returns the warning of incorrect vars
Error in `vector("list", ncol(data_numeric))`: invalid 'length' argument
Backtrace:
 1. testthat::expect_warning(...)
      at test-plot_hist_vars.R:17:2
 6. toRpEDA::plot_hist_vars(iris, c("Petal.Length", "Species"))
 7. base::vector("list", ncol(data_numeric))
      at toRpEDA/R/plot_histogram.R:62:2

Error (test-plot_hist_vars.R:22:3): Function returns the warning for none numeric vars specified only
Error in `parse_expr(x)`: `x` must contain exactly 1 expression, not 0.
Backtrace:
  1. testthat::expect_warning(plot_hist_vars(iris, c("Species")))
       at test-plot_hist_vars.R:22:2
  6. toRpEDA::plot_hist_vars(iris, c("Species"))
  9. ggplot2::aes_string(x = colnames(data_numeric)[i])
 10. base::lapply(...)
 11. ggplot2 (local) FUN(X[[i]], ...)
 12. rlang::parse_expr(x)

Error (test-plot_hist_vars.R:27:3): Function works correctly for different values of plots_per_page
Error in `parse_expr(x)`: `x` must contain exactly 1 expression, not 0.
Backtrace:
  1. testthat::expect_output(plot_hist_vars(mtcars, NULL, 3), "plot_layout")
       at test-plot_hist_vars.R:27:2
 10. toRpEDA::plot_hist_vars(mtcars, NULL, 3)
 13. ggplot2::aes_string(x = colnames(data_numeric)[i])
 14. base::lapply(...)
 15. ggplot2 (local) FUN(X[[i]], ...)
 16. rlang::parse_expr(x)
```
no idea what causes these, it could just be that I'm missing some dependencies or doing something wrong. I run these tests using `devtools::test()`.

**Comment by maciejors** [comment]
The function itself works properly and its code is beautifully written. There are only a few minor details that I'd like to point out:

1. I get warnings like these when I run examples from the function docs:
```r
> plot_hist_vars(mtcars, c("mpg", "cyl"))
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
Warning message:
`aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation ideoms with `aes()`
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
```
The first warning (the 'stat_bin()' one) seems to show up once per every plot, meaning if I use this function on a dataset with many continuous variables (like mtcars) I get loads of these in the console which is annoying.

2. There is some code below the function definition that I guess you just forgot to remove:
```r
data(mtcars)
plot_hist_vars(mtcars, c("mpg", "cyl"))
plot_hist_vars(iris, c("Sepal.Length", "Petal.Length", "Species"))
```

**Comment by Szymon-Gut** [comment]
Bins related warnings are gone. Test all passed. Code coverage is about 100 %.

**Review by maciejors — APPROVED** [review]
everything looks good now, great work

**Pull request merged**
